import re

# --- Simulated "Code Generation" Functions ---
# These functions represent the actual code that would be generated or executed
# based on a recognized intent. In a real AI-powered system, these would be
# complex code snippets or API calls generated by the AI.

def create_user_account(name, email):
    """Simulates creating a user account based on intent."""
    print(f"ACTION: Creating user account for '{name}' with email '{email}'...")
    # This line demonstrates the 'how' - the specific code or command generated
    print(f"  Generated/Executed Code: User.objects.create(name='{name}', email='{email}')")
    print("  Result: User account created successfully.")

def list_products(status="all"):
    """Simulates listing products based on intent."""
    print(f"ACTION: Listing products with status '{status}'...")
    # This line demonstrates the 'how' - the specific code or command generated
    print(f"  Generated/Executed Code: Product.query.filter_by(status='{status}').all()")
    print("  Result: Displaying product list...")
    # Simulate some data
    if status == "active":
        print("    - Product A (Active)")
        print("    - Product B (Active)")
    else:
        print("    - Product A (Active)")
        print("    - Product B (Active)")
        print("    - Product C (Inactive)")

def calculate_sum(num1, num2):
    """Simulates calculating a sum based on intent."""
    print(f"ACTION: Calculating sum of {num1} and {num2}...")
    # This line demonstrates the 'how' - the specific code or command generated
    print(f"  Generated/Executed Code: result = {num1} + {num2}")
    print(f"  Result: The sum is {num1 + num2}")

def send_welcome_email(recipient_name):
    """Simulates sending a welcome email based on intent."""
    print(f"ACTION: Sending welcome email to '{recipient_name}'...")
    # This line demonstrates the 'how' - the specific code or command generated
    print(f"  Generated/Executed Code: Mailer.send_email(template='welcome', to='{recipient_name}@example.com')")
    print(f"  Result: Welcome email sent to {recipient_name}.")

# --- Intent Processing Engine ---

def process_intent(intent_description: str):
    """
    Processes a natural language intent description and maps it to a specific action.
    This simulates the "understanding developer intentions" part of an AI system
    like Augmentcode Intent, translating 'what' the user wants into 'how' to do it.
    """
    print(f"\n--- Processing Intent: '{intent_description}' ---")

    # Intent 1: Create User
    match = re.search(r"create (?:a new )?user with name (\w+) and email (\S+)", intent_description, re.IGNORECASE)
    if match:
        name = match.group(1)
        email = match.group(2)
        # The AI system would recognize this intent and trigger the appropriate action/code generation.
        create_user_account(name, email)
        return

    # Intent 2: List Products
    match = re.search(r"list (?:all )?(active )?products", intent_description, re.IGNORECASE)
    if match:
        status = "active" if match.group(1) else "all"
        list_products(status)
        return

    # Intent 3: Calculate Sum
    match = re.search(r"calculate the sum of (\d+) and (\d+)", intent_description, re.IGNORECASE)
    if match:
        num1 = int(match.group(1))
        num2 = int(match.group(2))
        calculate_sum(num1, num2)
        return

    # Intent 4: Send Welcome Email
    match = re.search(r"send a welcome email to (\w+)", intent_description, re.IGNORECASE)
    if match:
        recipient = match.group(1)
        send_welcome_email(recipient)
        return

    print("  ERROR: Intent not recognized or parameters missing.")
    print("  Please try another intent, e.g., 'create user with name John and email john@example.com'")

# --- Main execution ---
if __name__ == "__main__":
    print("Welcome to the Intent-Based Programming Simulator!")
    print("This tool demonstrates how a system could interpret your 'intent' (what you want to do)")
    print("and translate it into specific actions or generated code ('how' to do it).")
    print("Type your intent, or 'exit' to quit.")

    while True:
        user_input = input("\nEnter your intent: ").strip()
        if user_input.lower() == 'exit':
            break
        process_intent(user_input)

    print("\nExiting Intent-Based Programming Simulator. Goodbye!")
